// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: T-HMI

#ifndef _T_HMI_UI_H
#define _T_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_gauge_empty_png);    // assets/gauge Empty.png
LV_IMG_DECLARE(ui_img_gauge_full_png);    // assets/Gauge Full.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
